version: '3.5'

services:
  client-dev:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    # nginx
    # ports:
    #   - '5000:80'
    # command: [nginx, '-g', 'daemon off;']